# Generated by Django 3.2.4 on 2021-12-01 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artemis', '0002_extraction_replicate'),
    ]

    operations = [
        migrations.CreateModel(
            name='CyVerseAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_token', models.TextField(blank=True, max_length=100)),
                ('api_token_expiration', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cyverse_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CyVerse Account',
                'ordering': ('-pk',),
            },
        ),
    ]
