# Generated by Django 3.2.4 on 2021-08-12 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artemis', '0003_rename_minerology_mineralogy'),
    ]

    operations = [
        migrations.AddField(
            model_name='mineralogy',
            name='replicate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artemis.replicate'),
        ),
    ]
