# Generated by Django 3.2.4 on 2021-08-12 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artemis', '0004_mineralogy_replicate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mineralogy',
            old_name='amorphus',
            new_name='amorphous',
        ),
    ]
