# Generated by Django 3.2.4 on 2021-08-13 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artemis', '0005_rename_amorphus_mineralogy_amorphous'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinate',
            name='plot',
        ),
        migrations.AddField(
            model_name='coordinate',
            name='replicate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artemis.replicate'),
        ),
    ]
