# Generated by Django 3.2.4 on 2021-08-24 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artemis', '0006_auto_20210813_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plot',
            name='EC_mean',
        ),
        migrations.RemoveField(
            model_name='plot',
            name='EC_sd',
        ),
        migrations.RemoveField(
            model_name='plot',
            name='pHCa_mean',
        ),
        migrations.RemoveField(
            model_name='plot',
            name='pHCa_sd',
        ),
        migrations.RemoveField(
            model_name='plot',
            name='pH_mean',
        ),
        migrations.RemoveField(
            model_name='plot',
            name='pH_sd',
        ),
        migrations.RemoveField(
            model_name='replicate',
            name='EC',
        ),
        migrations.RemoveField(
            model_name='replicate',
            name='pH',
        ),
        migrations.RemoveField(
            model_name='replicate',
            name='pHCa',
        ),
        migrations.AddField(
            model_name='geochemistry',
            name='pHCa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='replicate',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='replicate',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Coordinate',
        ),
    ]
